<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'brera\\magentoconnector\\xml\\product\\invalidimagedefinitionexception' => '/src/XmlBuilder/InvalidImageDefinitionException.php',
                'brera\\magentoconnector\\xml\\product\\productbuilder' => '/src/XmlBuilder/Product.php',
                'brera\\magentoconnector\\xml\\product\\productmerge' => '/src/XmlBuilder/Products.php',
                'brera\\magentoconnector\\xml\\product\\xmlbuildertest' => '/tests/XmlBuilder/ProductTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
