<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'brera\\magentoconnector\\xml\\product\\invalidimagedefinitionexception' => '/src/XmlBuilder/InvalidImageDefinitionException.php',
                'brera\\magentoconnector\\xml\\product\\productbuilder' => '/src/XmlBuilder/ProductBuilder.php',
                'brera\\magentoconnector\\xml\\product\\productbuildertest' => '/tests/XmlBuilder/ProductBuilderTest.php',
                'brera\\magentoconnector\\xml\\product\\productcontainer' => '/src/XmlBuilder/ProductContainer.php',
                'brera\\magentoconnector\\xml\\product\\productcontainertest' => '/tests/XmlBuilder/ProductContainerTest.php',
                'brera\\magentoconnector\\xml\\product\\productmerge' => '/src/XmlBuilder/ProductMerge.php',
                'brera\\magentoconnector\\xml\\product\\productmergetest' => '/tests/XmlBuilder/ProductMergeTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
