<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'brera\\magentoconnector\\api\\api' => '/src/Api/Api.php',
                'brera\\magentoconnector\\api\\apitest' => '/tests/Api/ApiTest.php',
                'brera\\magentoconnector\\api\\invalidhostexception' => '/src/Api/InvalidHostException.php',
                'brera\\magentoconnector\\api\\requestfailedexception' => '/src/Api/RequestFailedException.php',
                'brera\\magentoconnector\\xmlbuilder\\invalidimagedefinitionexception' => '/src/XmlBuilder/InvalidImageDefinitionException.php',
                'brera\\magentoconnector\\xmlbuilder\\productbuilder' => '/src/XmlBuilder/ProductBuilder.php',
                'brera\\magentoconnector\\xmlbuilder\\productbuildertest' => '/tests/XmlBuilder/ProductBuilderTest.php',
                'brera\\magentoconnector\\xmlbuilder\\productcontainer' => '/src/XmlBuilder/ProductContainer.php',
                'brera\\magentoconnector\\xmlbuilder\\productcontainertest' => '/tests/XmlBuilder/ProductContainerTest.php',
                'brera\\magentoconnector\\xmlbuilder\\productmerge' => '/src/XmlBuilder/ProductMerge.php',
                'brera\\magentoconnector\\xmlbuilder\\productmergetest' => '/tests/XmlBuilder/ProductMergeTest.php',
                'brera\\magentoconnector\\xmlbuilder\\stockbuilder' => '/src/XmlBuilder/StockBuilder.php',
                'brera\\magentoconnector\\xmlbuilder\\stockbuildertest' => '/tests/XmlBuilder/StockBuilderTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
