<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'lizardsandpumpkins\\magentoconnector\\api\\api' => '/src/Api/Api.php',
                'lizardsandpumpkins\\magentoconnector\\api\\apitest' => '/tests/Api/ApiTest.php',
                'lizardsandpumpkins\\magentoconnector\\api\\invalidhostexception' => '/src/Api/InvalidHostException.php',
                'lizardsandpumpkins\\magentoconnector\\api\\invalidurlexception' => '/src/Api/InvalidUrlException.php',
                'lizardsandpumpkins\\magentoconnector\\api\\requestfailedexception' => '/src/Api/RequestFailedException.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\catalogmerge' => '/src/XmlBuilder/CatalogMerge.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\catalogmergetest' => '/tests/XmlBuilder/CatalogMergeTest.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\invalidimagedefinitionexception' => '/src/XmlBuilder/InvalidImageDefinitionException.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\listingbuilder' => '/src/XmlBuilder/ListingBuilder.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\listingbuildertest' => '/tests/XmlBuilder/ListingBuilderTest.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\productbuilder' => '/src/XmlBuilder/ProductBuilder.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\productbuildertest' => '/tests/XmlBuilder/ProductBuilderTest.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\stockbuilder' => '/src/XmlBuilder/StockBuilder.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\stockbuildertest' => '/tests/XmlBuilder/StockBuilderTest.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\xmlstring' => '/src/XmlBuilder/XmlString.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\xmlstringtest' => '/tests/XmlBuilder/XmlStringTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
